dist: trusty
sudo: false
language: generic
install:
- python -m pip install --user pygments restructuredtext-lint
script:
- make -C ar
- make -C tar
- .private/update-readme
- git diff --exit-code
- restructuredtext-lint --encoding=UTF-8 README
- grep -Po '(?<=<)https:\S+/download/\S+(?=>)' README
  | wget -O /dev/null -nv -i -

# vim:ts=2 sts=2 sw=2 et
