dist: trusty
sudo: false
language: generic
addons:
  apt:
    packages:
    - python3-pip
    - python3-setuptools
install:
- python3 -m pip install --user pygments restructuredtext-lint
script:
- make -C ar
- make -C tar
- .private/update-readme
- git diff --exit-code
- grep -Po '(?<=<)https:\S+/download/\S+(?=>)' README
  | wget -O /dev/null -nv -i -
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
